# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2e72645ce1986531fd0d38995c8b1116e086cbc82e2ea3c9dbe2ea70faa44be9cbc0aab1bd1f2202e79dbaa7e0be6f50756f26217ebda56ef903c5e8dd2d03a

test:
  secret_key_base: 337eb67781e3c4b8b823fe5e0a2a9b2f48b830928c19de4979580f6d505f2bde40b34755ceb6b47acbaae50c141381ec4d6bb0f06e7c4f72064ebcd1e122cd74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
